import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { DndContext, DragEndEvent, DragOverlay, PointerSensor, closestCorners, useDroppable, useSensor, useSensors } from '@dnd-kit/core'
import { SortableContext, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import type { List, RecurringCompletion, RecurringTask, Rule, Task } from '../shared/types'
import './styles.css'
import './dark.css'
import './list-cards.css'
import './markdown.css'
import './task-lines.css'
import './date-range.css'
import './accent.css'
import './focus.css'

const api = async (url: string, options?: RequestInit) => { const response = await fetch(url, { headers: { 'Content-Type': 'application/json' }, ...options }); return response.status === 204 ? null : response.json() }
const iso = (d: Date) => d.toLocaleDateString('en-CA')
const dateFromIso = (value: string) => new Date(`${value}T12:00:00`)
const daysInRange = (startValue: string, endValue: string) => { const start = dateFromIso(startValue); const end = dateFromIso(endValue); const count = Math.max(1, Math.round((end.getTime() - start.getTime()) / 86400000) + 1); return Array.from({ length: count }, (_, i) => { const date = new Date(start); date.setDate(start.getDate() + i); return date }) }
const isRecurringOn = (task: RecurringTask, dateValue: string) => { const start = dateFromIso(task.start_date); const date = dateFromIso(dateValue); const difference = Math.round((date.getTime() - start.getTime()) / 86400000); if (difference < 0 || (task.end_date && dateValue >= task.end_date)) return false; if (task.recurring_rule === 'daily') return true; if (task.recurring_rule === 'weekdays') return ![0, 6].includes(date.getDay()); if (task.recurring_rule === 'weekly') return difference % 7 === 0; if (task.recurring_rule === 'biweekly') return difference % 14 === 0; if (task.recurring_rule === 'monthly') return date.getDate() === start.getDate(); return date.getDate() === start.getDate() && date.getMonth() === start.getMonth() }
function markup(text: string) { const parts = text.split(/(\*\*.*?\*\*|_.*?_)/g); return parts.map((part, i) => part.startsWith('**') ? <strong key={i}>{part.slice(2,-2)}</strong> : part.startsWith('_') ? <em className="markdown-italic" key={i}>{part.slice(1,-1)}</em> : part) }

function TaskCard({ task, onToggle, onDelete, onEdit }: { task: Task; onToggle: (task: Task) => void; onDelete:(id:string)=>void; onEdit:(task:Task,text:string, rule:Rule)=>void }) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: task.id, data: { task }, disabled: Boolean(task.recurring_task_id) })
  const [editing, setEditing] = useState(false); const [text, setText] = useState(task.text); const [rule, setRule] = useState<Rule>(task.recurring_rule)
  const style = { transform: CSS.Transform.toString(transform), transition, opacity: isDragging ? 0.25 : 1 }
  const commit = () => { setEditing(false); if (text.trim()) onEdit(task, text.trim(), rule); else onDelete(task.id) }
  return <div ref={setNodeRef} style={style} className={`task ${task.is_completed ? 'done' : ''}`} {...attributes} {...listeners}>
    <button className="check" onClick={() => onToggle(task)} aria-label="Complete task">{task.is_completed && '✓'}</button>
    {editing ? <div className="edit-wrap" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))commit()}}><input autoFocus value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')commit(); if(e.key==='Escape')setEditing(false)}}/><select value={rule ?? ''} onChange={e=>{const nextRule=(e.target.value || null) as Rule;setRule(nextRule);if(text.trim()){onEdit(task,text.trim(),nextRule);setEditing(false)}}}><option value="">does not repeat</option><option value="daily">daily</option><option value="weekdays">weekdays</option><option value="weekly">weekly</option><option value="biweekly">every 2 weeks</option><option value="monthly">monthly</option><option value="yearly">yearly</option></select></div> : <button className="task-text" onDoubleClick={()=>setEditing(true)} onClick={()=>setEditing(true)}>{markup(task.text)} {task.recurring_rule && <span className="repeat">↻</span>}</button>}
  </div>
}

function AddTask({ destination, onAdd }: { destination: {date?:string;list_id?:string}; onAdd:(text:string, destination:{date?:string;list_id?:string})=>void }) { const [text,setText]=useState(''); return <form className="add-task" onSubmit={e=>{e.preventDefault();if(text.trim()){onAdd(text.trim(),destination);setText('')}}}><span>+</span><input value={text} onChange={e=>setText(e.target.value)} placeholder="Add a task" aria-label="Add a task"/></form> }
function TaskList({tasks, destination, onToggle, onDelete, onEdit}:{tasks:Task[];destination:{date?:string;list_id?:string};onToggle:(t:Task)=>void;onDelete:(id:string)=>void;onEdit:(t:Task,text:string,r:Rule)=>void}) { const id=destination.date||destination.list_id!; const {setNodeRef,isOver}=useDroppable({id}); return <SortableContext items={tasks.map(t=>t.id)} strategy={verticalListSortingStrategy}><div ref={setNodeRef} className={`task-list ${isOver?'is-over':''}`}>{tasks.map(t=><TaskCard key={t.id} task={t} onToggle={onToggle} onDelete={onDelete} onEdit={onEdit}/>)}</div></SortableContext> }
function Column({ title, label, tasks, destination, onAdd, onToggle, onDelete, onEdit, today }: {title:string;label?:string;tasks:Task[];destination:{date?:string;list_id?:string};onAdd:AddTaskProps['onAdd'];onToggle:(t:Task)=>void;onDelete:(id:string)=>void;onEdit:(t:Task,text:string,r:Rule)=>void;today?:boolean}) { return <section className={`column ${today?'is-today':''}`}><header><span>{title}</span><b>{label}</b></header><TaskList tasks={tasks} destination={destination} onToggle={onToggle} onDelete={onDelete} onEdit={onEdit}/><AddTask destination={destination} onAdd={onAdd}/></section> }
type AddTaskProps={onAdd:(text:string,destination:{date?:string;list_id?:string})=>void}

function App() {
  const today=iso(new Date()); const defaultEnd=iso(new Date(Date.now()+6*86400000))
  const [tasks,setTasks]=useState<Task[]>([]); const [lists,setLists]=useState<List[]>([]); const [recurringTasks,setRecurringTasks]=useState<RecurringTask[]>([]); const [recurringCompletions,setRecurringCompletions]=useState<RecurringCompletion[]>([]); const [rangeStart,setRangeStart]=useState(today); const [rangeEnd,setRangeEnd]=useState(defaultEnd); const [focus,setFocus]=useState(false); const [dark,setDark]=useState(()=>localStorage.getItem('teuxdeux-theme')==='dark'); const [active,setActive]=useState<Task|null>(null)
  const days=useMemo(()=>daysInRange(rangeStart,rangeEnd),[rangeStart,rangeEnd]); const shiftRange=(direction:number)=>{const length=days.length;const start=dateFromIso(rangeStart);const end=dateFromIso(rangeEnd);start.setDate(start.getDate()+direction*length);end.setDate(end.getDate()+direction*length);setRangeStart(iso(start));setRangeEnd(iso(end))}
  const hydrate=(data:{tasks:Task[];lists:List[];recurringTasks:RecurringTask[];recurringCompletions:RecurringCompletion[]})=>{setTasks(data.tasks);setLists(data.lists);setRecurringTasks(data.recurringTasks);setRecurringCompletions(data.recurringCompletions)}
  useEffect(()=>{api('/api/bootstrap').then(hydrate)},[])
  useEffect(()=>{localStorage.setItem('teuxdeux-theme',dark?'dark':'light')},[dark])
  const persist = (next:Task[])=>{setTasks(next); api('/api/tasks/reorder',{method:'PUT',body:JSON.stringify(next.filter(t=>!t.recurring_task_id).map(t=>({id:t.id,date:t.date,list_id:t.list_id,sort_order:t.sort_order})))})}
  const add=(text:string,d:{date?:string;list_id?:string})=>api('/api/tasks',{method:'POST',body:JSON.stringify({text,date:d.date??null,list_id:d.list_id??null,sort_order:tasks.length})}).then(t=>setTasks(v=>[...v,t]))
  const toggle=(task:Task)=>{if(task.recurring_task_id){const is_completed=!task.is_completed;setRecurringCompletions(items=>is_completed?[...items,{recurring_task_id:task.recurring_task_id!,date:task.date!}]:items.filter(item=>!(item.recurring_task_id===task.recurring_task_id&&item.date===task.date)));api(`/api/recurring/${task.recurring_task_id}/completions`,{method:'POST',body:JSON.stringify({date:task.date,is_completed})});return}const next=tasks.map(t=>t.id===task.id?{...t,is_completed:!t.is_completed}:t);setTasks(next);api(`/api/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify({is_completed:!task.is_completed})}).then(()=>api('/api/bootstrap').then(hydrate))}
  const edit=(task:Task,text:string,recurring_rule:Rule)=>{if(task.recurring_task_id){const endpoint=recurring_rule?`/api/recurring/${task.recurring_task_id}`:`/api/recurring/${task.recurring_task_id}/disable`;const body=recurring_rule?{text,recurring_rule}:{date:task.date,is_completed:task.is_completed,text};api(endpoint,{method:recurring_rule?'PATCH':'POST',body:JSON.stringify(body)}).then(()=>api('/api/bootstrap').then(hydrate));return}const next=tasks.map(t=>t.id===task.id?{...t,text,recurring_rule}:t);setTasks(next);api(`/api/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify({text,recurring_rule})}).then(()=>api('/api/bootstrap').then(hydrate))}
  const remove=(id:string)=>{setTasks(v=>v.filter(t=>t.id!==id));api(`/api/tasks/${id}`,{method:'DELETE'})}
  const end=(event:DragEndEvent)=>{setActive(null);const {active,over}=event;if(!over)return;const source=tasks.find(t=>t.id===active.id); if(!source)return;const target=tasks.find(t=>t.id===over.id); const container=(target?.date || target?.list_id || String(over.id)) as string; if(!container)return;const isDate=/^\d{4}-\d{2}-\d{2}$/.test(container);let next=[...tasks];const sourceIndex=next.findIndex(t=>t.id===source.id);next.splice(sourceIndex,1); const insertAt=target ? next.findIndex(t=>t.id===target.id) : next.length;next.splice(insertAt<0?next.length:insertAt,0,{...source,date:isDate?container:null,list_id:isDate?null:container});const relevant=next.filter(t=>(isDate?t.date===container:t.list_id===container)).map((t,i)=>({...t,sort_order:i}));next=next.map(t=>relevant.find(x=>x.id===t.id)||t);persist(next)}
  const addList=()=>api('/api/lists',{method:'POST',body:JSON.stringify({title:'NEW LIST',sort_order:lists.length})}).then(l=>setLists(v=>[...v,l]))
  const rename=(list:List)=>{const title=window.prompt('List name',list.title);if(title?.trim()){setLists(v=>v.map(l=>l.id===list.id?{...l,title:title.trim()}:l));api(`/api/lists/${list.id}`,{method:'PATCH',body:JSON.stringify({title:title.trim()})})}}
  const removeList=(list:List)=>{if(window.confirm(`Remove ${list.title} and all of its tasks?`)){setLists(v=>v.filter(l=>l.id!==list.id));setTasks(v=>v.filter(t=>t.list_id!==list.id));api(`/api/lists/${list.id}`,{method:'DELETE'})}}
  const tasksFor=(date?:string,list?:string)=>{const normal=tasks.filter(t=>date?t.date===date:t.list_id===list);if(!date)return normal.sort((a,b)=>a.sort_order-b.sort_order);const repeated=recurringTasks.filter(task=>isRecurringOn(task,date)).map(task=>({id:`repeat:${task.id}:${date}`,recurring_task_id:task.id,text:task.text,is_completed:recurringCompletions.some(item=>item.recurring_task_id===task.id&&item.date===date),date,list_id:null,sort_order:task.sort_order,recurring_rule:task.recurring_rule}));return [...normal,...repeated].sort((a,b)=>a.sort_order-b.sort_order)}
  return <main className={dark?'dark':''}><header className="topbar"><div className="brand">teux<span>deux</span><i>✦</i></div><div className="week-nav"><button onClick={()=>shiftRange(-1)}>←</button><button className="today-button" onClick={()=>{setRangeStart(today);setRangeEnd(defaultEnd)}}>TODAY</button><button onClick={()=>shiftRange(1)}>→</button><div className="date-range"><input aria-label="Range start" type="date" value={rangeStart} onChange={e=>{setRangeStart(e.target.value);if(e.target.value>rangeEnd)setRangeEnd(e.target.value)}}/><span>—</span><input aria-label="Range end" type="date" min={rangeStart} value={rangeEnd} onChange={e=>setRangeEnd(e.target.value)}/></div></div><div className="actions"><button className={focus?'active':''} onClick={()=>setFocus(!focus)}>◉ FOCUS</button><button aria-label="Toggle dark mode" onClick={()=>setDark(value=>!value)}>{dark?'☀':'☾'}</button></div></header><div className={focus?'planner focus-view':'planner'}><div className="week-label">{days[0].toLocaleDateString('en-US',{month:'long',day:'numeric'})} — {days[days.length-1].toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</div><DndContext sensors={useSensors(useSensor(PointerSensor,{activationConstraint:{distance:5}}))} collisionDetection={closestCorners} onDragStart={e=>setActive(tasks.find(t=>t.id===e.active.id)||null)} onDragEnd={end}><div className="week-grid" style={focus ? undefined : {gridTemplateColumns:`repeat(${days.length},minmax(150px,1fr))`}}>{days.map(day=><Column key={iso(day)} title={iso(day)===today?'TODAY':day.toLocaleDateString('en-US',{weekday:'short'}).toUpperCase()} label={String(day.getDate()).padStart(2,'0')} today={iso(day)===today} tasks={tasksFor(iso(day))} destination={{date:iso(day)}} onAdd={add} onToggle={toggle} onDelete={remove} onEdit={edit}/>)}</div><section className="someday"><div className="someday-title"><span>SOMEDAY</span><small>Everything has its time.</small></div><div className="list-grid">{lists.map(list=><div className="bucket" key={list.id}><div className="bucket-header"><button className="list-name" onClick={()=>rename(list)}>{list.title} <small>✎</small></button><button className="remove-list" aria-label={`Remove ${list.title}`} onClick={()=>removeList(list)}>×</button></div><TaskList tasks={tasksFor(undefined,list.id)} destination={{list_id:list.id}} onToggle={toggle} onDelete={remove} onEdit={edit}/><AddTask destination={{list_id:list.id}} onAdd={add}/></div>)}<button className="new-list" onClick={addList}>+ NEW LIST</button></div></section><DragOverlay>{active&&<div className="task overlay">{active.text}</div>}</DragOverlay></DndContext></div><footer><span>Double-click a task to edit it. Use <b>**bold**</b> and <i>_italics_</i>.</span><span>made for calm, purposeful days</span></footer></main>
}
createRoot(document.getElementById('root')!).render(<App />)
